# Generated by Django 4.2.2 on 2023-06-17 12:37

from django.db import migrations, models
import django.db.models.deletion
import helpers.upload_files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dough_type', models.CharField(choices=[('THIN', 'Thin'), ('THICK', 'Thick')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=helpers.upload_files.upload_pizza_image)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizza.company')),
            ],
        ),
    ]
